# Generated by Django 3.1 on 2023-04-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('nomefantasia', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('inscricaoestadual', models.CharField(max_length=14, verbose_name='Inscrição Estadual')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=25, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(db_column='cpf', max_length=11, unique=True, verbose_name='CPF')),
                ('id_situacaocadastro', models.ForeignKey(db_column='id_situacaocadastro', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.situacaocadastro', verbose_name='Situação')),
                ('id_tipovisitante', models.ForeignKey(db_column='id_tipovisitante', on_delete=django.db.models.deletion.CASCADE, related_name='tipo_visitante', to='core.tipovisitante', verbose_name='Tipo Visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=12, verbose_name='Login')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('datahoraultimoacesso', models.DateTimeField(verbose_name='Data/Hora Ult. Acesso')),
                ('id_loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, to='core.loja', verbose_name='Loja')),
                ('id_situacaocadastro', models.ForeignKey(db_column='id_situacaocadastro', on_delete=django.db.models.deletion.CASCADE, related_name='situacao_usuario', to='core.situacaocadastro', verbose_name='Situacao')),
                ('id_tipousuario', models.ForeignKey(db_column='id_tipousuario', on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario', to='core.tipousuario', verbose_name='Tipo Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorVisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor', verbose_name='ID Fornecedor')),
                ('id_visitante', models.ForeignKey(db_column='id_visitante', on_delete=django.db.models.deletion.CASCADE, related_name='cod_visitante', to='core.visitante', verbose_name='ID Visitante')),
            ],
        ),
    ]
