# Generated by Django 3.1 on 2023-04-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datalanc', models.DateField()),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor', verbose_name='ID Fornecedor')),
                ('id_loja', models.ForeignKey(db_column='id_loja', on_delete=django.db.models.deletion.CASCADE, related_name='cod_loja', to='core.loja', verbose_name='ID Loja')),
                ('id_visitante', models.ForeignKey(db_column='id_visitante', on_delete=django.db.models.deletion.CASCADE, to='core.visitante', verbose_name='ID Visitante')),
            ],
        ),
    ]
